language: scala
scala:
  - "2.10.3"
jdk:
  - oraclejdk7
before_script:
  - ./ext/bin/install-ext-dependencies.sh
  - ./ext/bin/start-travis-cluster.sh -v
script:
  - sbt ++$TRAVIS_SCALA_VERSION "set logLevel in compile := Level.Warn" compile test
