language: scala
scala:
  - "2.10.3"
jdk:
  - oraclejdk7
before_script:
  - ./ext/bin/install-ext-dependencies.sh
  - ./ext/bin/start-test-cluster.sh
script:
  - sbt ++$TRAVIS_SCALA_VERSION compile
  - sbt ++$TRAVIS_SCALA_VERSION test
